"""Session titles and stop points (: the sidebar listed `Base directory for
th…`, `# AGENTS.md instructi…`, raw UUIDs and `[$spec]. One small fixture line per skip rule."""
from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

from pantheon.dispatch import sessions as sessions_mod
from pantheon.session_view import gitmarks
from pantheon.session_view import models as m
from pantheon.session_view import recent as recent_mod
from pantheon.session_view import titles
from pantheon.session_view import transcript as transcript_mod


def user(content, **extra) -> dict:
    return {"type": "user", "message": {"role": "user", "content": content}, **extra}


def cand(rec):
    got = titles.user_record_candidate(rec)
    return got[0] if got else None


# ---------------------------------------------------------------- skip rules, one each

def test_a_plain_first_message_is_the_title():
    assert cand(user("fix the launcher so F9 goes back to the deck")) == \
        "fix the launcher so F9 goes back to the deck"


def test_skill_body_is_skipped():
    rec = user([{"type": "text", "text": "Base directory for this skill: C:\\Home\\x\\skills\\spec\n\n# Spec"}])
    assert cand(rec) is None


def test_meta_records_are_skipped_even_with_ordinary_text():
    assert cand(user("Continue from where you left off.", isMeta=True)) is None


def test_command_wrapper_becomes_the_command_and_its_args():
    text = ("<command-message>orchestrate</command-message>\n<command-name>/orchestrate</command-name>\n"
            "<command-args>fix the deck</command-args>")
    assert titles.user_record_candidate(user(text)) == ("/orchestrate fix the deck", titles.STRONG)


def test_setup_commands_are_skipped():
    text = "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>fable</command-args>"
    assert cand(user(text)) is None


def test_a_bare_command_is_only_a_weak_title():
    text = "<command-name>/checkpoint</command-name><command-message>checkpoint</command-message><command-args></command-args>"
    assert titles.user_record_candidate(user(text)) == ("/checkpoint", titles.WEAK)


def test_agents_md_and_claude_md_injections_are_skipped():
    assert cand(user("# AGENTS.md instructions for C:\\Home\\x\\loom-os\n\n<INSTRUCTIONS>")) is None
    assert cand(user("# CLAUDE.md\nContents of C:\\x\\CLAUDE.md")) is None
    assert cand(user("Contents of C:\\Home\\x\\.claude\\CLAUDE.md (user's private)")) is None


def test_system_reminders_hook_output_and_local_command_output_are_skipped():
    assert cand(user("<system-reminder>be nice</system-reminder>")) is None
    assert cand(user("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>")) is None
    assert cand(user("<local-command-stdout>Set model to Fable</local-command-stdout>")) is None
    assert cand(user("Stop hook feedback:\n[powershell ...]: PRIVATE REPO PUSH GATE")) is None


def test_tool_results_are_skipped():
    rec = user([{"type": "tool_result", "tool_use_id": "t1", "content": "1\tLast updated"}])
    assert cand(rec) is None
    assert cand(user("ok", toolUseResult={"stdout": ""})) is None


def test_image_only_messages_are_skipped_and_image_markers_dropped():
    only_images = user([{"type": "image", "source": {"type": "base64", "data": "AAAA"}}])
    assert cand(only_images) is None
    mixed = user([{"type": "image", "source": {}}, {"type": "text", "text": "[Image #1] why is this red"}])
    assert cand(mixed) == "why is this red"


def test_compact_summaries_and_sidechains_are_skipped():
    assert cand(user("This session is being continued from a previous conversation that ran out")) is None
    assert cand(user("real words", isCompactSummary=True)) is None
    assert cand(user("sub-agent brief", isSidechain=True)) is None


def test_scheduled_task_runs_get_a_weak_readable_name():
    rec = user('<scheduled-task name="loom-os-night-wind-down" file="C:\\x\\SKILL.md">\nThis is an automated run')
    assert titles.user_record_candidate(rec) == ("scheduled: loom os night wind down", titles.WEAK)


def test_short_replies_are_weak():
    assert titles.user_record_candidate(user("Try again"))[1] == titles.WEAK


# ---------------------------------------------------------------- cleaning

def test_codex_skill_links_and_markdown_links_become_words():
    got = titles.text_candidate("[$spec](C:\\Home\\x\\\\.claude\\skills\\spec\\SKILL.md) I need reddit access")
    assert got[0] == "/spec I need reddit access"
    assert titles.readable("see [the docs](https://example.com/a/b) now") == "see the docs now"


def test_paths_shrink_to_their_last_part_but_word_pairs_survive():
    assert titles.readable('@"C:\\Home\\x\\Documents\\Projects\\file_inbox\\snap_p1.md" process it') == \
        "snap_p1.md process it"
    assert titles.readable("Read audit/2026-09-26-claude-brief.md and execute") == \
        "Read 2026-09-26-claude-brief.md and execute"
    assert titles.readable("spin up sonnet/opus agents and/or codex") == "spin up sonnet/opus agents and/or codex"


def test_html_entities_and_markdown_escapes_are_undone():
    assert titles.readable("&#x20;Validate the work in the condo\\_options folder") == \
        "Validate the work in the condo_options folder"


def test_brief_preambles_are_dropped():
    assert titles.polish("User asks 2026-09-26: Dispatch an agent to spec the speaker") == \
        "Dispatch an agent to spec the speaker"
    assert titles.polish("Read-only research for a spec, no edits or installs. Research Reddit API access") == \
        "Research Reddit API access"
    assert titles.polish("Use the log skill to separately record this failure") == \
        "/log separately record this failure"


def test_clip_cuts_at_a_word_boundary():
    text = "Audit current loom os work, write suggested improvements, possible choices"
    got = titles.clip(text, 44)
    assert got == "Audit current loom os work, write suggested…"
    assert len(got) <= 44


def test_untitled_names_project_and_age():
    assert titles.untitled("hiking_log_v2", "1d") == "untitled · hiking_log_v2 · 1d"
    assert titles.age_text(90) == "1m" and titles.age_text(7200) == "2h"


# ---------------------------------------------------------------- title_of on files

def write(path: Path, records) -> Path:
    path.write_text("".join(json.dumps(r) + "\n" for r in records), encoding="utf-8")
    return path


def test_custom_title_beats_ai_title_beats_first_user(tmp_path):
    p = write(tmp_path / "a.jsonl", [
        user("Base directory for this skill: x", isMeta=True),
        user("fix the hooks please"),
        {"type": "ai-title", "aiTitle": "Hook fixes"},
        {"type": "custom-title", "customTitle": "Pantheon session navigation issues"},
        {"type": "ai-title", "aiTitle": "Later ai title"},
    ])
    assert sessions_mod.title_of(p) == "Pantheon session navigation issues"


def test_ai_title_then_first_real_user_sentence(tmp_path):
    a = write(tmp_path / "b.jsonl", [user("fix it"), {"type": "ai-title", "aiTitle": "Worker deployment push"}])
    assert sessions_mod.title_of(a) == "Worker deployment push"
    b = write(tmp_path / "c.jsonl", [
        user("<local-command-caveat>Caveat</local-command-caveat>", isMeta=True),
        user("<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>"),
        user([{"type": "text", "text": "Base directory for this skill: C:\\s"}], isMeta=True),
        user("why does the deck crash on resize"),
    ])
    assert sessions_mod.title_of(b) == "why does the deck crash on resize"


def test_old_summary_records_count(tmp_path):
    p = write(tmp_path / "s.jsonl", [{"type": "summary", "summary": "Launcher rewrite", "leafUuid": "x"},
                                     user("go")])
    assert sessions_mod.title_of(p) == "Launcher rewrite"


def test_nothing_real_means_untitled_never_the_uuid(tmp_path):
    p = write(tmp_path / "c0ffee00-0000-4000-8000-000000000004.jsonl", [
        user("<command-name>/model</command-name><command-message>model</command-message><command-args>fable</command-args>"),
    ])
    assert sessions_mod.title_or_none(p) is None
    assert sessions_mod.title_of(p) == "untitled"


def test_title_found_in_the_tail_of_a_big_file_without_reading_the_middle(tmp_path, monkeypatch):
    monkeypatch.setattr(sessions_mod, "HEAD_LINES", 5)
    monkeypatch.setattr(sessions_mod, "TAIL_BYTES", 4_000)
    filler = [{"type": "assistant", "message": {"content": [{"type": "text", "text": "x" * 500}]}}] * 200
    p = write(tmp_path / "big.jsonl", [user("first words here")] + filler
              + [{"type": "custom-title", "customTitle": "Renamed at the end"}])
    assert sessions_mod.title_of(p) == "Renamed at the end"


def test_title_cache_notices_an_appended_rename(tmp_path):
    p = write(tmp_path / "grow.jsonl", [user("first words here")])
    assert sessions_mod.title_of(p) == "first words here"
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps({"type": "custom-title", "customTitle": "My rename"}) + "\n")
    assert sessions_mod.title_of(p) == "My rename"


def test_parser_title_uses_the_same_skip_rules(tmp_path):
    p = write(tmp_path / "t.jsonl", [
        user([{"type": "text", "text": "Base directory for this skill: C:\\s"}], isMeta=True),
        user("<command-name>/orchestrate</command-name><command-message>orchestrate</command-message><command-args>fix the deck</command-args>"),
    ])
    conv = transcript_mod.load(p)
    assert conv.title == "/orchestrate fix the deck"


# ---------------------------------------------------------------- Codex

def rollout(home: Path, thread_id: str, records) -> Path:
    folder = home / "sessions" / "2026" / "09" / "26"
    folder.mkdir(parents=True, exist_ok=True)
    return write(folder / f"rollout-2026-09-26T10-00-00-{thread_id}.jsonl", records)


def codex_user(text):
    return {"type": "response_item", "payload": {"type": "message", "role": "user",
                                                 "content": [{"type": "input_text", "text": text}]}}


def test_codex_skips_injected_turns_and_prefers_the_apps_thread_name(tmp_path):
    home = tmp_path / "codex"
    tid = "01900000-0000-7000-8000-000000000002"
    path = rollout(home, tid, [
        {"type": "session_meta", "payload": {"cwd": "C:\\x\\garden_plans", "thread_source": "user"}},
        codex_user("<recommended_plugins>\nHere is a list</recommended_plugins>"),
        codex_user("# AGENTS.md instructions for C:\\x\\garden_plans\n\n<INSTRUCTIONS>"),
        codex_user("<environment_context>\n  <cwd>C:\\x</cwd>"),
        codex_user("[$spec](C:\\Home\\x\\\\.claude\\skills\\spec\\SKILL.md) I need reddit access"),
    ])
    assert recent_mod._codex_title(path, home) == "/spec I need reddit access"
    (home / "session_index.jsonl").write_text(
        json.dumps({"id": tid, "thread_name": "Spec reliable Reddit access"}) + "\n", encoding="utf-8")
    assert recent_mod._codex_title(path, home) == "Spec reliable Reddit access"


def test_codex_guardian_threads_are_named_as_such(tmp_path):
    home = tmp_path / "codex"
    path = rollout(home, "01900000-0000-7000-8000-000000000003", [
        {"type": "session_meta", "payload": {"cwd": "C:\\x", "thread_source": "guardian_review"}},
        codex_user("The following is the Codex agent history whose request action you are assessing."),
    ])
    assert recent_mod._codex_title(path, home) == "Guardian review"


# ---------------------------------------------------------------- git stop points

def tool_use(tid, command, ts, name="Bash"):
    return {"type": "assistant", "timestamp": ts,
            "message": {"content": [{"type": "tool_use", "id": tid, "name": name,
                                     "input": {"command": command}}]}}


def tool_result(tid, is_error=False):
    return user([{"type": "tool_result", "tool_use_id": tid, "content": "ok", "is_error": is_error}])


def test_git_ops_reads_the_subcommand_not_prose():
    assert gitmarks.git_ops('git add -A && git commit -m "x" && git push') == {"commit", "push"}
    assert gitmarks.git_ops("git -C /c/repo push -u origin main") == {"push"}
    assert gitmarks.git_ops("git --no-pager log --oneline") == set()
    assert gitmarks.git_ops("claude -p 'use git and then commit the result'") == set()


def test_marks_count_only_successful_calls(tmp_path):
    p = write(tmp_path / "g.jsonl", [
        tool_use("t1", 'git commit -m "one"', "2026-09-26T10:00:00Z"), tool_result("t1"),
        tool_use("t2", "git push", "2026-09-26T10:05:00Z"), tool_result("t2"),
        tool_use("t3", 'git commit -m "nothing"', "2026-09-26T10:10:00Z"), tool_result("t3", is_error=True),
        tool_use("t4", 'git commit -am "two"', "2026-09-26T10:20:00Z", name="PowerShell"), tool_result("t4"),
    ])
    marks = gitmarks.marks_for(p)
    assert marks.last_commit_at == "2026-09-26T10:20:00Z"
    assert marks.last_push_at == "2026-09-26T10:05:00Z"
    conv = transcript_mod.load(p)
    assert (conv.last_commit_at, conv.last_push_at) == (marks.last_commit_at, marks.last_push_at)


def test_marks_read_only_the_appended_bytes(tmp_path):
    p = write(tmp_path / "inc.jsonl", [tool_use("t1", "git push", "2026-09-26T10:00:00Z")])
    assert gitmarks.marks_for(p).last_push_at is None   # no result yet
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(tool_result("t1")) + "\n")
    assert gitmarks.marks_for(p).last_push_at == "2026-09-26T10:00:00Z"


def test_codex_command_executions_count_on_exit_code_zero(tmp_path):
    def done(cmd, code, ts):
        return {"type": "event_msg", "timestamp": ts, "payload": {"type": "item_completed", "item": {
            "type": "CommandExecution", "command": ["pwsh.exe", "-Command", cmd], "exit_code": code}}}
    p = write(tmp_path / "rollout-x.jsonl", [
        done("git -C $repo commit -m x; git -C $repo push", "0", "2026-09-26T23:39:58Z"),
        done("git push", "1", "2026-09-26T23:50:00Z"),
    ])
    marks = gitmarks.marks_for(p)
    assert marks.last_push_at == "2026-09-26T23:39:58Z"
    assert marks.last_commit_at == "2026-09-26T23:39:58Z"


def test_stop_point_text_words():
    now = datetime(2026, 9, 26, 12, 0, tzinfo=timezone.utc)
    iso = lambda minutes: (now - timedelta(minutes=minutes)).isoformat().replace("+00:00", "Z")
    pushed = m.SessionEntry("s", m.RECENT, "p", "", "t", last_commit_at=iso(10), last_push_at=iso(4))
    committed = m.SessionEntry("s", m.RECENT, "p", "", "t", last_commit_at=iso(12), last_push_at=iso(90))
    never = m.SessionEntry("s", m.RECENT, "p", "", "t")
    assert gitmarks.stop_point_text(pushed, now) == "pushed 4m"
    assert gitmarks.stop_point_text(committed, now) == "committed 12m"
    assert gitmarks.stop_point_text(never, now) == "never pushed"


def test_recent_entries_carry_the_marks(tmp_path):
    home = tmp_path / "claude"
    folder = home / "projects" / "C--x-proj"
    folder.mkdir(parents=True)
    write(folder / "s1.jsonl", [
        {"type": "user", "cwd": "C:/x/proj", "message": {"content": "ship the thing"}},
        tool_use("t1", "git push", "2026-09-26T10:00:00Z"), tool_result("t1"),
    ])
    recent_mod._recent_cache.clear()
    out = recent_mod.recent_entries(None, limit=5, claude_home=home, codex_home=tmp_path / "none")
    assert out[0].title == "ship the thing"
    assert out[0].last_push_at == "2026-09-26T10:00:00Z"
